### PR TITLE
Updates for laravel 7

### PR DESCRIPTION
**Pull request by SiebeVE**
# This is a breaking change
See #16  for details

### CODE REVIEW

**Comment by SiebeVE** [comment]
Yes, you need a new transport added to the `mail.php` config.
This is documented in the `README.md`
https://github.com/SynergiTech/laravel-postal/pull/18/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by willpower232** [comment]
image

Already done I'm afraid.

**Comment by willpower232** [comment]
OH I hadn't fully checked out your code sorry

**Comment by SiebeVE** [comment]
I've tested it with a clean laravel 7 install and it appears to be working.

**Pull request merged**
