### PR TITLE
Modify the type loop to ensure to/cc/bcc data actually exists before …

### PR DESCRIPTION
**Pull request by death-droid**
…running the foreach loop

### CODE REVIEW

**Comment by forestlovewood** [comment]
Is the check necessary in this case? Because each type is already an array, the loop should just pass over them silently if no data exists.

**Comment by death-droid** [comment]
In my tests, it threw "Invalid argument supplied for foreach()" errors.

**Comment by forestlovewood** [comment]
Could you provide your tests? I'm not currently able to replicate the problem you're describing.

**Comment by death-droid** [comment]
Hi @forestlovewood,

I am just passing the user in for the "to" parameter and a Mailable class in then queueing it. 
`        Mail::to($request->user())
            ->queue(new PasswordChanged($request->user()));`

**Comment by Josh-G** [comment]
Seems like the documentation for swiftmailer SimpleMessage class is not correct:
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMessage.php#L33
It's defined as returning only array but can and will also return null.

We've pushed a commit to fix this. It will be released shortly. Thanks for your help.

**Pull request closed without merging**
